/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scientific_Calculate;


import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;



/**
 *
 * @author Ashen jayawardena
 */
public class Scientific_Cal extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    double operations;
    private Object math;
    HashMap <String, String> nameValue = new HashMap <String, String>();
    HashMap <String, String> formulaMap = new HashMap <String, String>();
    
    /**
     * Creates new form Scientific_Cal
     */
   List save = new ArrayList();
    public Scientific_Cal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jtxtDisplayin = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnPlusMinus = new javax.swing.JButton();
        jbtnDecimal = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnRoot = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnSin = new javax.swing.JButton();
        jbtnbra1 = new javax.swing.JButton();
        jbtnbra2 = new javax.swing.JButton();
        jbtnCos = new javax.swing.JButton();
        jbtnPi = new javax.swing.JButton();
        Integrate = new javax.swing.JButton();
        jbtnTan = new javax.swing.JButton();
        jbtnPower1 = new javax.swing.JButton();
        jbtnFact = new javax.swing.JButton();
        jbtnplot = new javax.swing.JButton();
        jbtnPercentage = new javax.swing.JButton();
        jbtnMod = new javax.swing.JButton();
        jtxtDisplayout = new javax.swing.JTextField();
        jbtnLog = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        addVariable = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSaveArera = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        Load = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WiCaDi Calculator");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtDisplayin.setEditable(false);
        jtxtDisplayin.setBackground(new java.awt.Color(51, 51, 51));
        jtxtDisplayin.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtxtDisplayin.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDisplayin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplayin.setCaretColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayin.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayin.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayinActionPerformed(evt);
            }
        });

        jbtn7.setBackground(new java.awt.Color(117, 117, 117));
        jbtn7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn7.setText("7");
        jbtn7.setAlignmentX(0.5F);
        jbtn7.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn9.setBackground(new java.awt.Color(117, 117, 117));
        jbtn9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn9.setForeground(new java.awt.Color(255, 255, 255));
        jbtn9.setText("9");
        jbtn9.setAlignmentX(0.5F);
        jbtn9.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnMinus.setBackground(new java.awt.Color(247, 154, 1));
        jbtnMinus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnMinus.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMinus.setText("-");
        jbtnMinus.setAlignmentX(0.5F);
        jbtnMinus.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });

        jbtn8.setBackground(new java.awt.Color(117, 117, 117));
        jbtn8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn8.setText("8");
        jbtn8.setAlignmentX(0.5F);
        jbtn8.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtnMultiply.setBackground(new java.awt.Color(247, 154, 1));
        jbtnMultiply.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMultiply.setText("*");
        jbtnMultiply.setAlignmentX(0.5F);
        jbtnMultiply.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplyActionPerformed(evt);
            }
        });

        jbtn6.setBackground(new java.awt.Color(117, 117, 117));
        jbtn6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn6.setText("6");
        jbtn6.setAlignmentX(0.5F);
        jbtn6.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn5.setBackground(new java.awt.Color(117, 117, 117));
        jbtn5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn5.setText("5");
        jbtn5.setAlignmentX(0.5F);
        jbtn5.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn4.setBackground(new java.awt.Color(117, 117, 117));
        jbtn4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn4.setText("4");
        jbtn4.setAlignmentX(0.5F);
        jbtn4.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtnDivide.setBackground(new java.awt.Color(247, 154, 1));
        jbtnDivide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnDivide.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDivide.setText("/");
        jbtnDivide.setAlignmentX(0.5F);
        jbtnDivide.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });

        jbtn3.setBackground(new java.awt.Color(117, 117, 117));
        jbtn3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn3.setText("3");
        jbtn3.setAlignmentX(0.5F);
        jbtn3.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn2.setBackground(new java.awt.Color(117, 117, 117));
        jbtn2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn2.setText("2");
        jbtn2.setAlignmentX(0.5F);
        jbtn2.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn1.setBackground(new java.awt.Color(117, 117, 117));
        jbtn1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn1.setText("1");
        jbtn1.setAlignmentX(0.5F);
        jbtn1.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtnEqual.setBackground(new java.awt.Color(247, 154, 1));
        jbtnEqual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnEqual.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEqual.setText("=");
        jbtnEqual.setAlignmentX(0.5F);
        jbtnEqual.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });

        jbtnPlusMinus.setBackground(new java.awt.Color(165, 165, 165));
        jbtnPlusMinus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnPlusMinus.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPlusMinus.setText("±");
        jbtnPlusMinus.setAlignmentX(0.5F);
        jbtnPlusMinus.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusMinusActionPerformed(evt);
            }
        });

        jbtnDecimal.setBackground(new java.awt.Color(117, 117, 117));
        jbtnDecimal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnDecimal.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDecimal.setText(".");
        jbtnDecimal.setAlignmentX(0.5F);
        jbtnDecimal.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecimalActionPerformed(evt);
            }
        });

        jbtn0.setBackground(new java.awt.Color(117, 117, 117));
        jbtn0.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtn0.setForeground(new java.awt.Color(255, 255, 255));
        jbtn0.setText("0");
        jbtn0.setAlignmentX(0.5F);
        jbtn0.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnBackspace.setBackground(new java.awt.Color(0, 51, 102));
        jbtnBackspace.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jbtnBackspace.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBackspace.setText("⌫");
        jbtnBackspace.setAlignmentX(0.5F);
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jbtnClear.setBackground(new java.awt.Color(165, 165, 165));
        jbtnClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClear.setText("C");
        jbtnClear.setAlignmentX(0.5F);
        jbtnClear.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnRoot.setBackground(new java.awt.Color(165, 165, 165));
        jbtnRoot.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnRoot.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRoot.setText("√");
        jbtnRoot.setAlignmentX(0.5F);
        jbtnRoot.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRootActionPerformed(evt);
            }
        });

        jbtnPlus.setBackground(new java.awt.Color(247, 154, 1));
        jbtnPlus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnPlus.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPlus.setText("+");
        jbtnPlus.setAlignmentX(0.5F);
        jbtnPlus.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });

        jbtnSin.setBackground(new java.awt.Color(165, 165, 165));
        jbtnSin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnSin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSin.setText("Sin");
        jbtnSin.setAlignmentX(0.5F);
        jbtnSin.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSinActionPerformed(evt);
            }
        });

        jbtnbra1.setBackground(new java.awt.Color(165, 165, 165));
        jbtnbra1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnbra1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbra1.setText("(");
        jbtnbra1.setAlignmentX(0.5F);
        jbtnbra1.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnbra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbra1ActionPerformed(evt);
            }
        });

        jbtnbra2.setBackground(new java.awt.Color(165, 165, 165));
        jbtnbra2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnbra2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbra2.setText(")");
        jbtnbra2.setAlignmentX(0.5F);
        jbtnbra2.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnbra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbra2ActionPerformed(evt);
            }
        });

        jbtnCos.setBackground(new java.awt.Color(165, 165, 165));
        jbtnCos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnCos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCos.setText("Cos");
        jbtnCos.setAlignmentX(0.5F);
        jbtnCos.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosActionPerformed(evt);
            }
        });

        jbtnPi.setBackground(new java.awt.Color(165, 165, 165));
        jbtnPi.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbtnPi.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPi.setText("π");
        jbtnPi.setAlignmentX(0.5F);
        jbtnPi.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPiActionPerformed(evt);
            }
        });

        Integrate.setBackground(new java.awt.Color(165, 165, 165));
        Integrate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Integrate.setForeground(new java.awt.Color(255, 255, 255));
        Integrate.setText("∫");
        Integrate.setAlignmentX(0.5F);
        Integrate.setBorder(new javax.swing.border.MatteBorder(null));
        Integrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegrateActionPerformed(evt);
            }
        });

        jbtnTan.setBackground(new java.awt.Color(165, 165, 165));
        jbtnTan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnTan.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTan.setText("Tan");
        jbtnTan.setAlignmentX(0.5F);
        jbtnTan.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTanActionPerformed(evt);
            }
        });

        jbtnPower1.setBackground(new java.awt.Color(165, 165, 165));
        jbtnPower1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbtnPower1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPower1.setText("X^Y");
        jbtnPower1.setAlignmentX(0.5F);
        jbtnPower1.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnPower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPower1ActionPerformed(evt);
            }
        });

        jbtnFact.setBackground(new java.awt.Color(165, 165, 165));
        jbtnFact.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbtnFact.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFact.setText("!");
        jbtnFact.setAlignmentX(0.5F);
        jbtnFact.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFactActionPerformed(evt);
            }
        });

        jbtnplot.setBackground(new java.awt.Color(165, 165, 165));
        jbtnplot.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnplot.setForeground(new java.awt.Color(255, 255, 255));
        jbtnplot.setText("Store");
        jbtnplot.setAlignmentX(0.5F);
        jbtnplot.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnplot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplotActionPerformed(evt);
            }
        });

        jbtnPercentage.setBackground(new java.awt.Color(165, 165, 165));
        jbtnPercentage.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnPercentage.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPercentage.setText("%");
        jbtnPercentage.setAlignmentX(0.5F);
        jbtnPercentage.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPercentageActionPerformed(evt);
            }
        });

        jbtnMod.setBackground(new java.awt.Color(165, 165, 165));
        jbtnMod.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbtnMod.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMod.setText("Mod");
        jbtnMod.setAlignmentX(0.5F);
        jbtnMod.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModActionPerformed(evt);
            }
        });

        jtxtDisplayout.setEditable(false);
        jtxtDisplayout.setBackground(new java.awt.Color(102, 102, 102));
        jtxtDisplayout.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtxtDisplayout.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDisplayout.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplayout.setCaretColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayout.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayout.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtxtDisplayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayoutActionPerformed(evt);
            }
        });

        jbtnLog.setBackground(new java.awt.Color(165, 165, 165));
        jbtnLog.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtnLog.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLog.setText("Log");
        jbtnLog.setAlignmentX(0.5F);
        jbtnLog.setBorder(new javax.swing.border.MatteBorder(null));
        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        addVariable.setBackground(new java.awt.Color(165, 165, 165));
        addVariable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addVariable.setForeground(new java.awt.Color(255, 255, 255));
        addVariable.setText(" Var(x)");
        addVariable.setAlignmentX(0.5F);
        addVariable.setBorder(new javax.swing.border.MatteBorder(null));
        addVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVariableActionPerformed(evt);
            }
        });

        jScrollPane3.setForeground(new java.awt.Color(0, 153, 153));

        jTextAreaSaveArera.setEditable(false);
        jTextAreaSaveArera.setBackground(new java.awt.Color(102, 102, 102));
        jTextAreaSaveArera.setColumns(20);
        jTextAreaSaveArera.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaSaveArera.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSaveArera);

        jMenuBar1.setBackground(new java.awt.Color(166, 166, 199));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard Calculator");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItem1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jMenuItem1VetoableChange(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific Calculator");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Graphs");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        Load.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        Load.setText("Load Formula");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });
        jMenu1.add(Load);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Save As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Stored Formulae");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnBackspace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDisplayin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtDisplayout))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnbra1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Integrate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jbtnbra2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnplot, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(addVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPower1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbtnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtDisplayin)
                                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtDisplayout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPower1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Integrate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnplot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnbra1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnbra2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(490, 430);
    }//GEN-LAST:event_formWindowActivated
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //standard calculator
        this.setResizable(true);
        this.setSize(250, 430);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Scientific calculator
        this.setResizable(true);
        this.setSize(490, 430);
        jtxtDisplayin.setSize(440,39);
        jtxtDisplayout.setSize(440,39);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtDisplayin.setText("");
        jtxtDisplayout.setText("");
        
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSinActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnSin.getText()+("(");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnSinActionPerformed

    private void jbtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnCos.getText()+("(");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnCosActionPerformed

    private void jbtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTanActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnTan.getText()+("(");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnTanActionPerformed

    private void jbtnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPercentageActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnPercentage.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnPercentageActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn7.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn8.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn9.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn4.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn5.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn6.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn1.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn2.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn3.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtn0.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String bsp = null;
        
        if (jtxtDisplayin.getText().length()>0){
            StringBuilder strB = new StringBuilder(jtxtDisplayin.getText());
            strB.deleteCharAt(jtxtDisplayin.getText().length()-1);
            bsp = strB.toString();
            jtxtDisplayin.setText(bsp);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecimalActionPerformed
        if (!jtxtDisplayin.getText().contains(".")){
            jtxtDisplayin.setText(jtxtDisplayin.getText()+ jbtnDecimal.getText());
        }
    }//GEN-LAST:event_jbtnDecimalActionPerformed

    private void jbtnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplayin.getText()));
        ops = ops*(-1);
        jtxtDisplayin.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnPlusMinusActionPerformed

    private void jbtnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRootActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnRoot.getText()+("(");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnRootActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnPlus.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnbra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbra1ActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnbra1.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnbra1ActionPerformed

    private void jtxtDisplayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayoutActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnMinus.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplyActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnMultiply.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnMultiplyActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnDivide.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFactActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnFact.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnFactActionPerformed

    private void jbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnMod.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnModActionPerformed

    private void jbtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogActionPerformed
        String iNum = jtxtDisplayin.getText()+("ln(");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnLogActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
    try{ 
        String str = jtxtDisplayin.getText();
    
        save.add(str);
        FormulaElement f = new FormulaElement() {};
        FormulaElement f2 = f.parseFormula(str); 
        for (String i : nameValue.keySet()) {
        f2.setVariableValue(i,Double.valueOf(nameValue.get(i)));
        }
       
        String answer = Float.toString((float) f2.evaluate());
        jtxtDisplayout.setText(answer);
        String saved = "";
        for(Object i:save){
          saved = saved + i.toString()+ "\n";
        }
        jTextAreaSaveArera.setText(saved);
        nameValue.clear();
    }catch(Exception e){
     jtxtDisplayout.setText("Syntax Error");
    }
        
    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPiActionPerformed
        String iNum = jtxtDisplayin.getText()+jbtnPi.getText();
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnPiActionPerformed

    private void jbtnPower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPower1ActionPerformed
        String iNum = jtxtDisplayin.getText()+("^");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnPower1ActionPerformed

    private void IntegrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegrateActionPerformed
        
    }//GEN-LAST:event_IntegrateActionPerformed

    private void jbtnbra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbra2ActionPerformed
       String iNum = jtxtDisplayin.getText()+(")");
        jtxtDisplayin.setText(iNum);
    }//GEN-LAST:event_jbtnbra2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       new Graph();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jtxtDisplayinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayinActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown
     
  
   
    private void jbtnplotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplotActionPerformed
        JFrame frame = new JFrame();
        String name = JOptionPane.showInputDialog(frame, "Enter function name: ");
        
        formulaMap.put(name,jtxtDisplayin.getText());
    }//GEN-LAST:event_jbtnplotActionPerformed

    private void addVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVariableActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        String name = JOptionPane.showInputDialog(frame, "Enter variable name (one letter only):");
        String value = JOptionPane.showInputDialog(frame, "Enter variable value (leave blank to store as a function):");
        nameValue.put(name,value);
        String result = jtxtDisplayin.getText()+name; 
        jtxtDisplayin.setText(result);
         //   System.out.println(result);
        
       
    }//GEN-LAST:event_addVariableActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
        JFileChooser fs = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        
        int returnValue = fs.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) { 
        File ls = fs.getSelectedFile();
        String result="";
        String line="";
        
        try (BufferedReader br = new BufferedReader(new FileReader(ls.getPath()))) {
                while ((line = br.readLine()) != null) {      
                // use comma as separator
                String[] formula = line.split(",");
                for(String s:formula){
                 result=result + s;
                }
                
                jtxtDisplayin.setText(result);

                }  

        } catch (IOException e) {
            e.printStackTrace();
        }

        }
      
    }//GEN-LAST:event_LoadActionPerformed

    private void jMenuItem1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jMenuItem1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1VetoableChange

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         FileWriter writer;
           
        FormulaElement f = new FormulaElement(){};
        String str = jtxtDisplayin.getText();
        FormulaElement f2 = f.parseFormula(str); 
        String csv = f.getCSV();
        JFileChooser fs = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        fs.setFileFilter(new FileNameExtensionFilter("Comma Seperated Values (*.csv)", ".csv"));
        int returnValue = fs.showSaveDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fs.getSelectedFile();
                char buffer[]= new char[csv.length()];
                csv.getChars(0, csv.length(), buffer, 0);
                writer = new FileWriter(selectedFile.getAbsolutePath()+".csv");
                try {
                    writer.write(buffer);
                } catch (IOException ex) {
                    Logger.getLogger(Scientific_Cal.class.getName()).log(Level.SEVERE, null, ex);
                }
                writer.close();
                System.out.println(selectedFile.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(Scientific_Cal.class.getName()).log(Level.SEVERE, null, ex);
            }
		}
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Formulae Library");
        frame.setSize(450, 250);
         DefaultListModel<String> model = new DefaultListModel<>();
        JList<String> list = new JList<>( model );
        JButton use =new JButton("use");
        use.setBounds(0,170,80,30);  
        //use.setPreferredSize(new Dimension(40, 40));
        
        
       
        
        for(String s:formulaMap.keySet()){
          model.addElement(s);
        } 
        if(formulaMap.size()==0){
         model.addElement("You have no stored formulae");
        }
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list.setSelectedIndex(0);
        
        list.setVisibleRowCount(5);
        JScrollPane listScrollPane = new JScrollPane(list);
        frame.add(use);
        frame.add(list);
        
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
         use.addActionListener(new ActionListener(){  
         public void actionPerformed(ActionEvent e){ 
            String output=list.getSelectedValue(); 
            String result= formulaMap.get(output);
            jtxtDisplayin.setText(result);  
        }  
        });  
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Integrate;
    private javax.swing.JMenuItem Load;
    private javax.swing.JButton addVariable;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaSaveArera;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCos;
    private javax.swing.JButton jbtnDecimal;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnFact;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMod;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnPercentage;
    private javax.swing.JButton jbtnPi;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnPlusMinus;
    private javax.swing.JButton jbtnPower1;
    private javax.swing.JButton jbtnRoot;
    private javax.swing.JButton jbtnSin;
    private javax.swing.JButton jbtnTan;
    private javax.swing.JButton jbtnbra1;
    private javax.swing.JButton jbtnbra2;
    private javax.swing.JButton jbtnplot;
    private javax.swing.JTextField jtxtDisplayin;
    private javax.swing.JTextField jtxtDisplayout;
    // End of variables declaration//GEN-END:variables
}
